Repository Encamina/enmarcha, pull requests merged in 2023-12, with the labels that each got.

#20 Update main.yml
  .github/workflows/main.yml
Labels: enhancement

#22 Updated `main.yml` GitHub Actions workflow.
  .github/workflows/main.yml
Labels: enhancement

#25 Testing why CD is not working.
  .github/workflows/main.yml
Labels: bug

#33 Fix slow issue with ILengthFunctions
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/ILengthFunctions.cs
Labels: bug, enhancement

#35 Issue #34. Semantic kernel summaries plugin fails to preserve the original language of the text
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Text/Plugins/TextPlugin/Summarize/config.json
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Text/Plugins/TextPlugin/Summarize/skprompt.txt
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Text/PluginsInfo.cs
Labels: bug, enhancement

#38 add model 3.5 turbol 16k
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.AI.OpenAI.Abstractions/ModelInfo.cs
Labels: enhancement

#37 @apicazo/add 35turbo16k model
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.AI.OpenAI.Abstractions/ModelInfo.cs
Labels: enhancement
