Repository Encamina/enmarcha, pull requests merged in 2024-01, with the labels that each got.

#45 Fix BuildConfiguration enviromental variable in .github/workflows/main.yml #31
  .github/workflows/main.yml
  CHANGELOG.md
  Directory.Build.props
Labels: bug

#46 Improvements on ephemeral memory handler.
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/MemoryStoreHandlerBase.cs
  src/Encamina.Enmarcha.SemanticKernel/EphemeralMemoryStoreHandler.cs
Labels: enhancement

#47 Improvements in `Encamina.Enmarcha.SemanticKernel.Connectors.Document`
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.Net.Http/MediaTypeFileExtensionMapper.cs
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/DefaultDocumentContentExtractor.cs
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/DocumentContentExtractorBase.cs
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/Extensions/IServiceCollectionExtensions.cs
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/IDocumentConnectorProvider.cs
Labels: enhancement

#48 @rliberoff/improvements on ephemaral memory handler
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/IDocumentConnectorProvider.cs
Labels: enhancement

#49 Various improvements in IMemoryStore, IMemoryManager and IMemoryStoreHandler.
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/IMemoryManager.cs
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/IMemoryStoreHandler.cs
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/MemoryStoreHandlerBase.cs
  src/Encamina.Enmarcha.SemanticKernel/EphemeralMemoryStoreHandler.cs
  src/Encamina.Enmarcha.SemanticKernel/MemoryManager.cs
Labels: enhancement

#51 Removed unnecessary `Guards` when adding a Memory Manager and the Ephemeral Memory Store Handler. The exceptions will be thrown by the DI engine itself.
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.SemanticKernel/Extensions/IServiceCollectionExtensions.cs
Labels: enhancement

#52 Modified dependency injection lifetime for `MemoryManager` and `EphemeralMemoryStoreHandler` services.
  CHANGELOG.md
  Directory.Build.props
  README.md
  src/Encamina.Enmarcha.SemanticKernel/Extensions/IServiceCollectionExtensions.cs
Labels: enhancement

#53 Fixing DI lifecycles for Memory Managers and update related methods.
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/IMemoryManager.cs
  src/Encamina.Enmarcha.SemanticKernel/Extensions/IServiceCollectionExtensions.cs
  src/Encamina.Enmarcha.SemanticKernel/MemoryManager.cs
Labels: bug, enhancement

#54 Update Memory Manager
  CHANGELOG.md
  Directory.Build.props
  samples/SemanticKernel/Encamina.Enmarcha.Samples.SemanticKernel.QuestionAnswering/ExampleQuestionAnsweringFromMemory..cs
  samples/SemanticKernel/Encamina.Enmarcha.Samples.SemanticKernel.QuestionAnswering/MockMemoryInformation.cs
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/IMemoryManager.cs
  src/Encamina.Enmarcha.SemanticKernel/EphemeralMemoryStoreHandler.cs
  src/Encamina.Enmarcha.SemanticKernel/MemoryManager.cs
Labels: bug, enhancement

#57 Added optional parameter to `AddDefaultDocumentConnectorProvider` and `AddDefaultDocumentContentExtractor`
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/Extensions/IServiceCollectionExtensions.cs
Labels: enhancement

#59 Added event handler for `MemoryManager` operations.
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/Encamina.Enmarcha.SemanticKernel.Abstractions.csproj
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/Events/MemoryManagerEventArgs.cs
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/Events/MemoryManagerEventTypes.cs
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/IMemoryManager.cs
  src/Encamina.Enmarcha.SemanticKernel/Extensions/IServiceCollectionExtensions.cs
  src/Encamina.Enmarcha.SemanticKernel/MemoryManager.cs
Labels: enhancement

#61 Fixed bug on IMemoryManager events
  Directory.Build.props
  src/Encamina.Enmarcha.SemanticKernel/Extensions/IServiceCollectionExtensions.cs
  src/Encamina.Enmarcha.SemanticKernel/MemoryManager.cs
Labels: bug

#66 Added `IMemoryStoreExtender` class
  CHANGELOG.md
  Directory.Build.props
  samples/SemanticKernel/Encamina.Enmarcha.Samples.SemanticKernel.QuestionAnswering/ExampleQuestionAnsweringFromMemory..cs
  samples/SemanticKernel/Encamina.Enmarcha.Samples.SemanticKernel.QuestionAnswering/MockMemoryInformation.cs
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/Events/MemoryManagerEventArgs.cs
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/Events/MemoryManagerEventTypes.cs
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/Events/MemoryStoreEventArgs.cs
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/Events/MemoryStoreEventTypes.cs
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/IMemoryStoreExtender.cs
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/IMemoryStoreHandler.cs
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/MemoryStoreHandlerBase.cs
  src/Encamina.Enmarcha.SemanticKernel/EphemeralMemoryStoreHandler.cs
  src/Encamina.Enmarcha.SemanticKernel/Extensions/IServiceCollectionExtensions.cs
  src/Encamina.Enmarcha.SemanticKernel/MemoryManager.cs
  src/Encamina.Enmarcha.SemanticKernel/MemoryStoreExtender.cs
Labels: enhancement
