Repository Encamina/enmarcha, pull requests merged in 2024-03, with the labels that each got.

#82 Updated dependencies and added feature to delete chat history messages from `ChatHistoryProvider`
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.AI.OpenAI.Azure/AzureOpenAIOptions.cs
  src/Encamina.Enmarcha.AI.OpenAI.Azure/Encamina.Enmarcha.AI.OpenAI.Azure.csproj
  src/Encamina.Enmarcha.Data.Abstractions/IAsyncRepository.cs
  src/Encamina.Enmarcha.Data.Abstractions/IAsyncWriteRepository.cs
  src/Encamina.Enmarcha.Data.Cosmos/CosmosRepository{T}.cs
  src/Encamina.Enmarcha.Email.MailKit/Encamina.Enmarcha.Email.MailKit.csproj
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/IChatHistoryProvider.cs
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Chat/ChatHistoryProvider.cs
  src/Encamina.Enmarcha.Testing.Smtp/Encamina.Enmarcha.Testing.Smtp.csproj
  src/Encamina.Enmarcha.Testing/Encamina.Enmarcha.Testing.csproj
Labels: enhancement

#83 Add KeyedNamed services
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Memory/Extensions/IServiceCollectionExtensions.cs
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Memory/README.md
Labels: enhancement

#84 Added semantic text chunker
  CHANGELOG.md
  Directory.Build.props
  Enmarcha.sln
  src/Encamina.Enmarcha.AI.Abstractions/BreakpointThresholdType.cs
  src/Encamina.Enmarcha.AI.Abstractions/ISemanticTextSplitter.cs
  src/Encamina.Enmarcha.AI.Abstractions/SemanticTextSplitterOptions.cs
  src/Encamina.Enmarcha.AI/Encamina.Enmarcha.AI.csproj
  src/Encamina.Enmarcha.AI/Extensions/IServiceCollectionExtensions.cs
  src/Encamina.Enmarcha.AI/TextSplitters/SemanticTextSplitter.cs
  src/Encamina.Enmarcha.Core/MathUtils.cs
  tst/Encamina.Enmarcha.AI.Tests/SemanticTextSplitterTests.cs
  tst/Encamina.Enmarcha.Core.Tests/Encamina.Enmarcha.Core.Tests.csproj
  tst/Encamina.Enmarcha.Core.Tests/MathUtilsTests.cs
  tst/Encamina.Enmarcha.Core.Tests/Usings.cs
Labels: enhancement

#85 Fixed `DeleteAsync<TEntityId>` method in `CosmosRepository<T>`
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.Data.Cosmos/CosmosRepository{T}.cs
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Chat/ChatHistoryProvider.cs
Labels: bug, enhancement

#87 Added new function to delete chat messages history in `ChatWithHistoryPlugin`.
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Chat/Plugins/ChatWithHistoryPlugin.cs
Labels: enhancement

#89 @lmarcos/add semantic document extractor
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.AI.Abstractions/IDocumentContentExtractor.cs
  src/Encamina.Enmarcha.Core/MathUtils.cs
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/DefaultDocumentContentExtractor.cs
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/DefaultDocumentContentSemanticExtractor.cs
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/DocumentContentExtractorBase.cs
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/DocumentContentSemanticExtractorBase.cs
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/Encamina.Enmarcha.SemanticKernel.Connectors.Document.csproj
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/Extensions/IServiceCollectionExtensions.cs
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/IDocumentConnectorProvider.cs
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/IDocumentConnectorUtils.cs
  tst/Encamina.Enmarcha.Core.Tests/MathUtilsTests.cs
Labels: bug, enhancement

#90 Improved SemanticTextSplitter
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.AI.Abstractions/SemanticTextSplitterOptions.cs
  src/Encamina.Enmarcha.AI/TextSplitters/SemanticTextSplitter.cs
  tst/Encamina.Enmarcha.AI.Tests/SemanticTextSplitterTests.cs
Labels: enhancement

#93 CI/CD Actions - Node 16 Actions will be deprecated by October 23rd, 2024
  .github/workflows/main.yml
Labels: enhancement

#94 Fix CI/CD pipeline.
  .github/workflows/main.yml
Labels: bug

#92 CodeQL Action v2 will be deprecated on December 5th, 2024.
  .github/workflows/codeql.yml
  Directory.Build.props
Labels: enhancement

#100 Update Semantic Kernel to 1.6.2 to fix issue with `JsonSchema.Net.Generation` package to resolve dependency conflict
  CHANGELOG.md
  Directory.Build.props
  samples/SemanticKernel/Encamina.Enmarcha.Samples.SemanticKernel.QuestionAnswering/Encamina.Enmarcha.Samples.SemanticKernel.QuestionAnswering.csproj
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/Encamina.Enmarcha.SemanticKernel.Abstractions.csproj
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/Encamina.Enmarcha.SemanticKernel.Connectors.Document.csproj
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Memory/Encamina.Enmarcha.SemanticKernel.Connectors.Memory.csproj
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Chat/Encamina.Enmarcha.SemanticKernel.Plugins.Chat.csproj
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Memory/Encamina.Enmarcha.SemanticKernel.Plugins.Memory.csproj
  src/Encamina.Enmarcha.SemanticKernel.Plugins.QuestionAnswering/Encamina.Enmarcha.SemanticKernel.Plugins.QuestionAnswering.csproj
Labels: bug, enhancement
