Repository Encamina/enmarcha, pull requests merged in 2024-02, with the labels that each got.

#68 Bump version from `8.1.1` to `8.1.2`. This is the new final version for release 8.1.2
  CHANGELOG.md
  Directory.Build.props
  Enmarcha.sln
  samples/SemanticKernel/Encamina.Enmarcha.Samples.SemanticKernel.QuestionAnswering/Encamina.Enmarcha.Samples.SemanticKernel.QuestionAnswering.csproj
  src/Encamina.Enmarcha.AI.Abstractions/TextSplitterOptions.cs
  src/Encamina.Enmarcha.AspNet.Mvc/Bindings/FormToDictionaryModelBinder.cs
  src/Encamina.Enmarcha.Bot.Abstractions/Encamina.Enmarcha.Bot.Abstractions.csproj
  src/Encamina.Enmarcha.Bot/Encamina.Enmarcha.Bot.csproj
  src/Encamina.Enmarcha.Core/Debouncer.cs
  src/Encamina.Enmarcha.Data.AzureAISearch/AzureAISearchOptions.cs
  src/Encamina.Enmarcha.Data.AzureAISearch/Encamina.Enmarcha.Data.AzureAISearch.csproj
  src/Encamina.Enmarcha.Data.AzureAISearch/Properties/CompilerFeatureRequiredAttribute.cs
  src/Encamina.Enmarcha.Data.AzureAISearch/Properties/IsExternalInit.cs
  src/Encamina.Enmarcha.Data.AzureAISearch/Properties/RequiredMemberAttribute.cs
  src/Encamina.Enmarcha.Data.AzureAISearch/Properties/SetsRequiredMembersAttribute.cs
  src/Encamina.Enmarcha.Data.Cosmos/Encamina.Enmarcha.Data.Cosmos.csproj
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/Encamina.Enmarcha.SemanticKernel.Abstractions.csproj
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/Encamina.Enmarcha.SemanticKernel.Connectors.Document.csproj
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Memory/Encamina.Enmarcha.SemanticKernel.Connectors.Memory.csproj
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Memory/Extensions/IServiceCollectionExtensions.cs
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Chat/Encamina.Enmarcha.SemanticKernel.Plugins.Chat.csproj
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Memory/Encamina.Enmarcha.SemanticKernel.Plugins.Memory.csproj
  src/Encamina.Enmarcha.SemanticKernel.Plugins.QuestionAnswering/Encamina.Enmarcha.SemanticKernel.Plugins.QuestionAnswering.csproj
Labels: enhancement

#69 Added Description property to VersionSwaggerGenOptions
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.AspNet.OpenApi.Swashbuckle/VersionSwaggerGenConfigureOptions.cs
  src/Encamina.Enmarcha.AspNet.OpenApi.Swashbuckle/VersionSwaggerGenOptions.cs
Labels: enhancement

#73 Temporary workaround for handling Http NotFound exception in MemoryStoreExtender
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.SemanticKernel/MemoryStoreExtender.cs
Labels: bug

#76 Added locale parameter to QuestionAnsweringPlugin functions
  CHANGELOG.md
  Directory.Build.props
  samples/SemanticKernel/Encamina.Enmarcha.Samples.SemanticKernel.QuestionAnswering/TestQuestionAnswering.cs
  src/Encamina.Enmarcha.SemanticKernel.Plugins.QuestionAnswering/Plugins/QuestionAnsweringPlugin.cs
  src/Encamina.Enmarcha.SemanticKernel.Plugins.QuestionAnswering/PluginsInfo.cs
Labels: enhancement

#78 Bump version `8.1.3` - Introduced `IChatHistoryProvider` interface and its corresponding implementation `ChatHistoryProvider`.
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.Data.Cosmos/Extensions/IServiceCollectionExtensions.cs
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/IChatHistoryProvider.cs
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/ILengthFunctions.cs
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Chat/ChatHistoryProvider.cs
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Chat/Extensions/IServiceCollectionExtensions.cs
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Chat/Extensions/KernelExtensions.cs
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Chat/Options/ChatHistoryProviderOptions.cs
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Chat/Options/ChatWithHistoryPluginOptions.cs
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Chat/Plugins/ChatWithHistoryPlugin.cs
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Chat/README.md
  src/Encamina.Enmarcha.SemanticKernel/Encamina.Enmarcha.SemanticKernel.csproj
Labels: documentation, enhancement

#79 Remove MemoryStoreExtender workaround
  CHANGELOG.md
  Directory.Build.props
  samples/Data/Encamina.Enmarcha.Samples.Data.EntityFramework/Encamina.Enmarcha.Samples.Data.EntityFramework.csproj
  samples/SemanticKernel/Encamina.Enmarcha.Samples.SemanticKernel.QuestionAnswering/Encamina.Enmarcha.Samples.SemanticKernel.QuestionAnswering.csproj
  src/Encamina.Enmarcha.AI.Abstractions/Encamina.Enmarcha.AI.Abstractions.csproj
  src/Encamina.Enmarcha.AI.OpenAI.Azure/Encamina.Enmarcha.AI.OpenAI.Azure.csproj
  src/Encamina.Enmarcha.AI.TextsTranslation.Azure/Encamina.Enmarcha.AI.TextsTranslation.Azure.csproj
  src/Encamina.Enmarcha.AI/Encamina.Enmarcha.AI.csproj
  src/Encamina.Enmarcha.AspNet.Mvc/Encamina.Enmarcha.AspNet.Mvc.csproj
  src/Encamina.Enmarcha.Core/Encamina.Enmarcha.Core.csproj
  src/Encamina.Enmarcha.Data.Cosmos/Encamina.Enmarcha.Data.Cosmos.csproj
  src/Encamina.Enmarcha.Data.EntityFramework/Encamina.Enmarcha.Data.EntityFramework.csproj
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/Encamina.Enmarcha.SemanticKernel.Abstractions.csproj
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/Encamina.Enmarcha.SemanticKernel.Connectors.Document.csproj
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Memory/Encamina.Enmarcha.SemanticKernel.Connectors.Memory.csproj
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Chat/Encamina.Enmarcha.SemanticKernel.Plugins.Chat.csproj
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Memory/Encamina.Enmarcha.SemanticKernel.Plugins.Memory.csproj
  src/Encamina.Enmarcha.SemanticKernel.Plugins.QuestionAnswering/Encamina.Enmarcha.SemanticKernel.Plugins.QuestionAnswering.csproj
  src/Encamina.Enmarcha.SemanticKernel/MemoryStoreExtender.cs
  src/Encamina.Enmarcha.Testing/Encamina.Enmarcha.Testing.csproj
  tst/Directory.Build.targets
Labels: bug, enhancement

#80 @lmarcos/sk question function improvements
  CHANGELOG.md
  Directory.Build.props
  src/Encamina.Enmarcha.SemanticKernel.Plugins.QuestionAnswering/Plugins/QuestionAnsweringPlugin.cs
Labels: enhancement

#81 Updated dependencies:
  CHANGELOG.md
  Directory.Build.props
  samples/SemanticKernel/Encamina.Enmarcha.Samples.SemanticKernel.QuestionAnswering/Encamina.Enmarcha.Samples.SemanticKernel.QuestionAnswering.csproj
  src/Encamina.Enmarcha.AI.IntentsPrediction.Azure/Encamina.Enmarcha.AI.IntentsPrediction.Azure.csproj
  src/Encamina.Enmarcha.Bot.Abstractions/Encamina.Enmarcha.Bot.Abstractions.csproj
  src/Encamina.Enmarcha.Bot/Encamina.Enmarcha.Bot.csproj
  src/Encamina.Enmarcha.SemanticKernel.Abstractions/Encamina.Enmarcha.SemanticKernel.Abstractions.csproj
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/Encamina.Enmarcha.SemanticKernel.Connectors.Document.csproj
  src/Encamina.Enmarcha.SemanticKernel.Connectors.Memory/Encamina.Enmarcha.SemanticKernel.Connectors.Memory.csproj
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Chat/Encamina.Enmarcha.SemanticKernel.Plugins.Chat.csproj
  src/Encamina.Enmarcha.SemanticKernel.Plugins.Memory/Encamina.Enmarcha.SemanticKernel.Plugins.Memory.csproj
  src/Encamina.Enmarcha.SemanticKernel.Plugins.QuestionAnswering/Encamina.Enmarcha.SemanticKernel.Plugins.QuestionAnswering.csproj
  tst/Directory.Build.targets
Labels: enhancement
